name: lego_trading_manager
description: Arcturus mobile app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  socket_io_client: ^3.0.2

  # Database
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.2

  # Storage / paths
  path: ^1.9.0
  path_provider: ^2.1.4

  # Device / network
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.2.3

  # Utils
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true