version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "20m"
    max-file: "5"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: arcturus_api
    restart: always
    ports:
      - "4000:4000"
    logging: *default-logging

  workers:
    build:
      context: .
      dockerfile: apps/workers/Dockerfile
    container_name: arcturus_workers
    restart: always
    logging: *default-logging

  scrapers:
    build:
      context: .
      dockerfile: apps/scrapers/Dockerfile
    container_name: arcturus_scrapers
    restart: always
    logging: *default-logging