export const QUEUE_NAMES = {
  SCRAPERS: 'scrapers',
  MARKET: 'market',
  DECISIONS: 'decisions',
  MAINTENANCE: 'maintenance',
  SYNC: 'sync',
} as const;

export const JOB_NAMES = {
  RUN_SCANNER: 'run-scanner',
  RECOMPUTE_MARKET_SNAPSHOTS: 'recompute-market-snapshots',
  RECOMPUTE_DECISIONS: 'recompute-decisions',
  DETECT_DEALS: 'detect-deals',
  SCHEDULED_REFRESH: 'scheduled-refresh',
  MARK_STALE_LISTINGS: 'mark-stale-listings',
  SOURCE_HEALTH_ROLLUP: 'source-health-rollup',
  CLEANUP_OLD_SNAPSHOTS: 'cleanup-old-snapshots',
  GLOBAL_SYNC_REFRESH: 'global-sync-refresh',
  PORTFOLIO_REBALANCING: 'portfolio-rebalancing',
  SURGE_PRICING: 'surge-pricing',
  C2C_STORAGE_FEE: 'c2c-storage-fee',
  DUTCH_AUCTION: 'dutch-auction',
  LOGISTICS_SENTINEL: 'logistics-sentinel',
  MONOPOLY_SQUEEZE: 'monopoly-squeeze',
  ZERO_TOUCH_MATCHER: 'zero-touch-matcher',
  AI_SMM_BROADCASTER: 'ai-smm-broadcaster',
  LTV_MAXIMIZER: 'ltv-maximizer',
  SURGE_SCOUTS: 'surge-scouts',
  VAULT_REPORTS: 'vault-reports',
} as const;